version: '3.8'

services:
  nginx:
    container_name: gateway-az-app
    image: nginx:1.25
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./nginx/conf/prod/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf/custom_error_pages/502.html:/etc/nginx/html/custom_error_pages/502.html
    networks:
      - az_app_network
    depends_on:
      - az-app
    restart: always

  az-app:
    container_name: az-app
    image: az-app
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    command: npm run start:prod:api
    networks:
      - az_app_network

networks:
  az_app_network:
    driver: bridge
